server:
  port: 8080
  servlet:
    context-path: /sell
spring:
  datasource:
    url: jdbc:mysql://localhost/sell?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
logging:
  level:
    com.example.mybatis.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true
wechat:
  wxAppId: wxa830230a1a818a46
  wxAppSecret: 6d2141b57fc59362f9f631f89d0243c7
  baseHttp: http://47.98.161.153
  templateId:
    orderStatus: tJgwhhVYNoFEk3EDcRO2vJG-5DZVi4Xnk4CGTZhB8Pw