server:
  port: 8088
  servlet:
    context-path: /sell
spring:
  datasource:
    url: jdbc:mysql://47.98.161.153/sell?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: a123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
logging:
  level:
    com.example.mybatis.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true